# Generated by Django 5.1.1 on 2024-10-22 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadernoEncargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento_n', models.CharField(max_length=255)),
                ('contrato_celebrado', models.DateField()),
                ('periodo_vigencia', models.CharField(max_length=255)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=100)),
                ('cumprimento_prazo', models.BooleanField()),
                ('penalidade', models.BooleanField()),
                ('justificar_prazo', models.TextField(blank=True, null=True)),
                ('defeitos', models.TextField(blank=True, null=True)),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
