# Generated by Django 5.1.1 on 2024-10-23 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contract_estado_alter_contract_plurianual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadernoEncargos',
            new_name='CadernoEncargo',
        ),
    ]
