# Generated by Django 5.1.1 on 2024-10-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_cadernoencargos_cadernoencargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='estado',
            new_name='_estado',
        ),
    ]
