# Generated by Django 5.1.1 on 2024-10-23 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_estado_contract__estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('prazo', models.CharField(max_length=255)),
                ('preco_contratual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('valor_entregue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorrente', models.BooleanField(default=False)),
                ('compromisso', models.BooleanField(default=False)),
                ('plurianual', models.TextField(blank=True, null=True)),
                ('_estado', models.BooleanField(default=False)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
