# Generated by Django 5.1.1 on 2024-10-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename__estado_contract_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
