# Generated by Django 5.1.1 on 2024-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_historico_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tipo_produto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='tipo_produto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
