# Generated by Django 5.1.1 on 2024-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contract_tipo_produto_historico_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='iva',
            field=models.DecimalField(choices=[(0.06, '6%'), (0.13, '13%'), (0.23, '23%')], decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
