# Generated by Django 5.1.1 on 2024-10-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cadernoencargo_group_contract_group_historico_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadernoencargo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='group',
        ),
    ]
