# Generated by Django 5.0.9 on 2024-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_cadernoencargo_group_remove_contract_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='alerta_prazo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='alerta_valor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='alerta_prazo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='alerta_valor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
