# Generated by Django 5.0.9 on 2024-11-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contract_alerta_prazo_contract_alerta_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='alerta_valor',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='alerta_valor',
        ),
    ]
