# Generated by Django 5.0.9 on 2024-11-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_contract_alerta_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='prazo',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ContratoAnoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_anuais', to='main.contract')),
            ],
            options={
                'unique_together': {('contrato', 'ano')},
            },
        ),
    ]
