# Generated by Django 5.0.9 on 2024-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_contract_prazo_contratoanovalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='plurianual_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prazo',
            field=models.CharField(max_length=255),
        ),
    ]
