# Generated by Django 5.0.9 on 2024-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_contract_plurianual_values_alter_contract_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='plurianual_values',
        ),
        migrations.DeleteModel(
            name='ContratoAnoValor',
        ),
    ]
