# Generated by Django 5.0.3 on 2024-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_contract_plurianual_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='anos_plurianual',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
