# Generated by Django 5.0.9 on 2024-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_contract_anos_plurianual'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='iva_str',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
